### PR TITLE
Add conda environment to test PyTorch

### PR DESCRIPTION
**Pull request by matthewfeickert**
For Travis to run tests with PyTorch as a backend it needs to be able to install PyTorch. As PyTorch can't be (easily) installed through `pip` use `conda` to do so.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@lukasheinrich I think that this is actually okay to merge. [From the logs](https://travis-ci.org/lukasheinrich/pyhf/jobs/338488979) it seems that the environment seems to be getting setup okay, but then the tests themselves are what is causing things to fail:
```
The command "pyflakes pyhf" exited with 1.
```
If this is expected behavior given the rest of the `pytorch` PR then I think it is okay to accept this.

**Comment by matthewfeickert** [comment]
@lukasheinrich Done. I did a force push and the tests are running again.

**Comment by matthewfeickert** [comment]
@lukasheinrich `pyflakes` still fails, so tonight I'll see if I can get the Trusty Docker container Travis uses and then step through the process and recreate the issue.

**Comment by lukasheinrich** [comment]
@matthewfeickert looking at the changed files it's still pulling changes from the pytorch branch. Maybe creating a compeltely new PR works?

**Comment by matthewfeickert** [comment]
Closing this PR as PR #65 fixes this issue.

**Pull request closed without merging**
